version: 1
formatters:
  simple:
    format: '{"time": %(asctime)s, "name": %(name)s, "severity": %(levelname)s, "message": %(message)s, "row": "%(lineno)d}, "module": "%(module)s", "filename": "%(filename)s"'
handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple
    stream: ext://sys.stdout
loggers:
  sampleLogger:
    level: DEBUG
    handlers: [console]
    propagate: no
root:
  level: DEBUG
  handlers: [console]